In [1]:
import numpy as np


In [2]:
my_list1 = [1,2,3,4
           ]

In [3]:
my_array1 = np.array(my_list1)

In [4]:
my_array1


array([1, 2, 3, 4])

In [5]:
my_list1

[1, 2, 3, 4]

In [6]:
my_list2 = [11,22,33,44]


In [7]:
my_list2


[11, 22, 33, 44]

In [8]:
my_list2[2]


33

In [9]:
my_lists = [my_list1,my_list2]

In [10]:
my_array2 = np.array(my_lists
                    )

In [11]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [12]:
my_array2.shape

(2, 4)

In [13]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [14]:
np.empty


<function numpy.core.multiarray.empty>

In [15]:
np.empty(5)


array([  6.91481856e-310,   4.67515591e-310,   3.05167986e+030,
         1.30435301e-037,   2.37151510e-322])

In [16]:
np.eye(5)


array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [ ]:
np.arange()