In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[0:5] = 100

In [8]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr = np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
slice_of_array = arr[0:6]

In [14]:
slice_of_array[:] = 99

In [15]:
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [16]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [17]:
arr_copy = arr.copy

In [19]:
arr_2d = np.array(([1,2,3],[11,22,33],[21,22,23]))

In [20]:
arr_2d

array([[ 1,  2,  3],
       [11, 22, 33],
       [21, 22, 23]])

## arr_

In [21]:
arr_2d[1]

array([11, 22, 33])

In [22]:
array[0]

NameError: name 'array' is not defined

In [23]:
arr_2d[0][2]

3

In [24]:
arr_2d[0:1][0:1]

array([[1, 2, 3]])

In [27]:
arr_2d[0:2,1:]

array([[ 2,  3],
       [22, 33]])

In [26]:
arr_2d

array([[ 1,  2,  3],
       [11, 22, 33],
       [21, 22, 23]])

In [28]:
arr_2d[0,1:]

array([2, 3])

In [29]:
arr_2d[:,1:]

array([[ 2,  3],
       [22, 33],
       [22, 23]])

In [30]:
arr_2d[:2,1:]

array([[ 2,  3],
       [22, 33]])

In [32]:
arr2d = np.zeros([10,10])

## 

In [33]:
arr2d


array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [34]:
arr_length = arr2d.shape[1]

In [35]:
arr_length

10

In [38]:
for i in range(arr_length):
    arr2d[i][i] = i

In [39]:
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [40]:
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])