In [1]:
import numpy as np
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [2]:
# SAVE array

np.save('myarray',arr)

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# LOAD array

np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [5]:
# SAVE MULTIPLE ARRAYS

arr1 = np.load('myarray.npy')
arr2 = arr

# SAVE AS A ZIP

np.savez('ziparray.npz', x = arr1, y = arr2)

In [6]:
#LOAD ZIP FILES

archive_array = np.load('ziparray.npz')

In [7]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [8]:
# SAVE TEXT ARRAY

arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('mytextarray.txt',arr,delimiter=',')

In [9]:
arr = np.loadtxt('mytextarray.txt',delimiter=',')
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [10]:
arr[0]

array([ 1.,  2.,  3.])

In [11]:
arr[0][1]

2.0