In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
A = np.random.randn(10)

In [5]:
A

array([ 0.62340753, -1.9835374 ,  0.46764885,  0.28255256, -1.38634089,
        2.00281847,  0.47025291, -0.6764028 ,  0.3045482 ,  0.5293634 ])

In [6]:
B = np.random.randn(10)

In [7]:
B

array([-1.21635615, -0.3043259 ,  0.3562935 , -0.10646855, -1.58348175,
       -0.30003283,  1.06488881,  0.42688998, -1.44390697,  0.40222143])

In [8]:
np.maximum(A,B)

array([ 0.62340753, -0.3043259 ,  0.46764885,  0.28255256, -1.38634089,
        2.00281847,  1.06488881,  0.42688998,  0.3045482 ,  0.5293634 ])

In [9]:
import webbrowser
