In [1]:
# Now we'll learn about concatenating along an axis
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
# in Numpy

arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
# in Pandas

ser1 = Series([0,1,2],index=['T','U','V'])

In [6]:
ser2 = Series([3,4],index=['X','Y'])

In [7]:
ser1

T    0
U    1
V    2
dtype: int64

In [8]:
ser2

X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2]) #axis=0 by default

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [11]:
# add markers

pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [13]:
# Dataframe concatenation
dframe1 = DataFrame(np.random.randn(4,3),columns = ['x','y','z'])

In [14]:
dframe2 = DataFrame(np.random.randn(3,3),columns = ['y','q','x'])

In [15]:
dframe1

x         y         z
0 -1.308484 -0.601821  2.013438
1 -1.904868 -0.039254  0.205418
2 -1.235085  1.397291  1.289369
3  0.898442 -0.095967 -0.006053

In [16]:
dframe2

y         q         x
0  0.491773 -0.290332  0.499198
1 -1.408752  1.609003 -0.062878
2  0.059319 -1.811423 -2.213636

In [17]:
pd.concat([dframe1,dframe2])

q         x         y         z
0       NaN -1.308484 -0.601821  2.013438
1       NaN -1.904868 -0.039254  0.205418
2       NaN -1.235085  1.397291  1.289369
3       NaN  0.898442 -0.095967 -0.006053
0 -0.290332  0.499198  0.491773       NaN
1  1.609003 -0.062878 -1.408752       NaN
2 -1.811423 -2.213636  0.059319       NaN

In [18]:
# ignore index

pd.concat([dframe1,dframe2],ignore_index=True)

q         x         y         z
0       NaN -1.308484 -0.601821  2.013438
1       NaN -1.904868 -0.039254  0.205418
2       NaN -1.235085  1.397291  1.289369
3       NaN  0.898442 -0.095967 -0.006053
4 -0.290332  0.499198  0.491773       NaN
5  1.609003 -0.062878 -1.408752       NaN
6 -1.811423 -2.213636  0.059319       NaN